title: Gurkeerat Singh Kakar
description: Data science & analytics portfolio of Gurkeerat Singh Kakar — Computing Science student at the University of Alberta.
theme: null
markdown: kramdown
permalink: pretty
includes_dir: includes
